version: "3.7"

services:
  node:
    image: node:lts-alpine
    container_name: node_backend
    volumes:
      - ./node:/app
    working_dir: /app
    environment:
      - NODE_ENV=test
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example1234
      - DB_NAME=test
      - DB_DROP_SCHEMA=true
      - SERVER_USE_CONFIG=true
    ports:
      - "8080" # express port
      - "8081" # restify port
      - "9229:9229"
    labels:
      - "traefik.frontend.rule=Host:node.docker.localhost"
    command: yarn ci:test
