version: "3.7"

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  db:
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    depends_on:
      - reverse-proxy
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example1234
      MYSQL_USER: test
      MYSQL_DATABASE: test
    labels:
      - "traefik.enable=false"
      # - "traefik.frontend.rule=Host:mysql.docker.localhost"
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   labels:
  #     - "traefik.enable=false"
  #     - "traefik.frontend.rule=Host:redis.docker.localhost"
